# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGuwahatischool():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_guwahatischool(self):
    # Test name: guwahati school
    # Step # | name | target | value
    # 1 | open | https://www.google.com/maps/@24.8899575,92.8874496,15z?entry=ttu&g_ep=EgoyMDI1MTIwOS4wIKXMDSoASAFQAw%3D%3D | 
    self.driver.get("https://www.google.com/maps/@24.8899575,92.8874496,15z?entry=ttu&g_ep=EgoyMDI1MTIwOS4wIKXMDSoASAFQAw%3D%3D")
    # 2 | setWindowSize | 1936x1048 | 
    self.driver.set_window_size(1936, 1048)
    # 3 | mouseOver | css=.KNfEk:nth-child(3) > .e2moi | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".KNfEk:nth-child(3) > .e2moi")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | click | id=searchboxinput | 
    self.driver.find_element(By.ID, "searchboxinput").click()
    # 5 | type | id=searchboxinput | schools in maligaon, guwahati
    self.driver.find_element(By.ID, "searchboxinput").send_keys("schools in maligaon, guwahati")
    # 6 | sendKeys | id=searchboxinput | ${KEY_ENTER}
    self.driver.find_element(By.ID, "searchboxinput").send_keys(Keys.ENTER)
    # 7 | click | css=div:nth-child(3) .hfpxzc | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) .hfpxzc").click()
    # 8 | click | css=.RcCsl:nth-child(3) .Cw1rxd | 
    self.driver.find_element(By.CSS_SELECTOR, ".RcCsl:nth-child(3) .Cw1rxd").click()
    # 9 | click | css=.RcCsl:nth-child(5) .Cw1rxd | 
    self.driver.find_element(By.CSS_SELECTOR, ".RcCsl:nth-child(5) .Cw1rxd").click()
    # 10 | click | css=.DUwDvf | 
    self.driver.find_element(By.CSS_SELECTOR, ".DUwDvf").click()
    # 11 | click | css=.lMbq3e | 
    self.driver.find_element(By.CSS_SELECTOR, ".lMbq3e").click()
    # 12 | click | css=.H1VXrf:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".H1VXrf:nth-child(1)").click()
    # 13 | mouseOver | css=.JXAzz:nth-child(1) img | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".JXAzz:nth-child(1) img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 14 | mouseOut | css=.JXAzz:nth-child(1) img | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 15 | click | css=.fxNQSd:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".fxNQSd:nth-child(1)").click()
    # 16 | click | css=div:nth-child(5) > .Nv2PK > .hfpxzc | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > .Nv2PK > .hfpxzc").click()
    # 17 | click | css=.RcCsl:nth-child(3) .Cw1rxd | 
    self.driver.find_element(By.CSS_SELECTOR, ".RcCsl:nth-child(3) .Cw1rxd").click()
    # 18 | click | css=.RcCsl:nth-child(5) .g88MCb .Cw1rxd | 
    self.driver.find_element(By.CSS_SELECTOR, ".RcCsl:nth-child(5) .g88MCb .Cw1rxd").click()
    # 19 | click | css=.RcCsl:nth-child(6) .Cw1rxd | 
    self.driver.find_element(By.CSS_SELECTOR, ".RcCsl:nth-child(6) .Cw1rxd").click()
    # 20 | click | css=.RcCsl:nth-child(7) .etWJQ:nth-child(1) .Cw1rxd | 
    self.driver.find_element(By.CSS_SELECTOR, ".RcCsl:nth-child(7) .etWJQ:nth-child(1) .Cw1rxd").click()
    # 21 | click | css=.lMbq3e | 
    self.driver.find_element(By.CSS_SELECTOR, ".lMbq3e").click()
    # 22 | click | css=.fxNQSd:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".fxNQSd:nth-child(1)").click()
  
